#ifndef _LIGHTINTERFACE_H_
#define _LIGHTINTERFACE_H_

#include <core/Common.h>
#include <core/RayCompressed.h>
#include <core/RandomGenerator.h>

MSC_NAMESPACE_BEGIN

/**
 * @brief      Abstract interface class for light sources
 */
class LightInterface
{
public:
  virtual ~LightInterface() {}

  /**
   * @brief      Illumination of mulitple positions on a geometric surface
   *
   * @param[in]  <unnamed>  amount of positions to be illuminated
   * @param      _random    thread local random generator to prevent mutation
   * @param      _position  array of position data
   * @param      _input     array of input directions generated by light for surface evaluation
   * @param      _radiance  array of radiance values for surface postions
   */
  virtual void illuminate(const unsigned int _size, RandomGenerator* _random, Vector3f* _position, Vector3f* _input, Colour3f* _radiance) const =0;
};

MSC_NAMESPACE_END

#endif
